export const KPI_CODES = {
    // Stock
    STOCK_VALUE_TOTAL: "STOCK_VALUE_TOTAL",
    STOCK_BY_SHOP: "STOCK_BY_SHOP",
    STOCK_BY_SEGMENT: "STOCK_BY_SEGMENT",
    STOCK_DORMANT: "STOCK_DORMANT",
    STOCK_OUT_OF_STOCK: "STOCK_OUT_OF_STOCK",
    STOCK_LOW: "STOCK_LOW",
    STOCK_TURNOVER: "STOCK_TURNOVER",
    STOCK_DISCREPANCY: "STOCK_DISCREPANCY",

    // Commercial
    SALES_REVENUE: "SALES_REVENUE",
    SALES_MARGIN: "SALES_MARGIN",
    SALES_TOP_PRODUCTS: "SALES_TOP_PRODUCTS",

    // Finance
    FINANCE_CASH: "FINANCE_CASH",
    FINANCE_DSO: "FINANCE_DSO",

    // Opérations
    OPS_LATE_DELIVERY: "OPS_LATE_DELIVERY",

    // RH
    HR_HEADCOUNT: "HR_HEADCOUNT",
} as const;

export type KpiCode = keyof typeof KPI_CODES;